# Generated by Django 2.1.4 on 2018-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('occupation', models.IntegerField()),
                ('city_category', models.IntegerField()),
                ('stay_years', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('purchase', models.IntegerField()),
            ],
        ),
    ]
